In [2]:
import sys
import numpy as np

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
# shows all elements after index 0 (including index 0)
a[0:]

array([1, 2, 3, 4])

In [9]:
# doesn't include index 3 (or 4th position)
a[1:3]

array([2, 3])

In [10]:
# from index 1 to (not including) very last index [-1]
a[1:-1]

array([2, 3])

In [11]:
# shows index 0 and index 2 only
a[::2]

array([1, 3])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:
# an arry of indexes (similar to above execution)
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
# checking data type of array
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [20]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [21]:
c = np.array(['a', 'b', 'c'])

In [22]:
# Unicode (python 3)
c.dtype

dtype('<U1')

In [23]:
# array of an object; not often used for individual objects like this
d = np.array([{'a': 1}, sys])

In [24]:
d.dtype

dtype('O')

# Dimensions & shapes

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
# 2 by 3 (2 rows/arrays, 3 columns)
A.shape

(2, 3)

In [28]:
# number of dimensions (array(s) inside of a whole array)
A.ndim

2

In [29]:
# total number of elements
A.size

6

In [30]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [31]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [32]:
# 2 by 2 by 3 (2 sections, 2 arrays/rows in each section, 3 columns)
B.shape

(2, 2, 3)

In [33]:
# array(s) inside of array(s) instead of a whole array;
B.ndim

3

In [34]:
# total number of elements
B.size

12

In [35]:
# if dimensions sections are not equal (like below), python will see it as a type object
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\prisc\AppData\Local\Temp/ipykernel_19024/548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [36]:
C.dtype

dtype('O')

In [37]:
C.shape

(2,)

In [38]:
# since it is seen as type object, the sections are seen as single elements
C.size

2

In [39]:
type(C[0])

list

# Indexing & Slicing of Matrices

In [40]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [41]:
# shows all elements in array for index 1
A[1]

array([4, 5, 6])

In [42]:
# shows index 0 of index 1 array
A[1][0]

4

In [43]:
# another way of writing above execution; A[d1, d2, d3, ..., dn]
A[1, 0]

4

In [44]:
# shows arrays from index 0 to index 2 (not including index 2)
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
# shows index 0 to 2 (not including 2; ':2') for all arrays (':')
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
# shows first 2 elements (':2') of first 2 arrays (':2')
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [47]:
# shows last element (index 2; '2:') of first 2 arrays ('2:')
A[:2, 2:]

array([[3],
       [6]])

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# mutable: changing array after it has been assigned; changing index 1 array (2nd position)
A[1] = np.array([10, 10, 10])

In [50]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [51]:
# changes all elements in index 2 array to '99'
A[2] = 99

In [52]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary Statistics

In [53]:
a1 = np.array([1, 2, 3, 4])

In [54]:
a1.sum()

10

In [55]:
a1.mean()

2.5

In [56]:
# standard deviation
a1.std()

1.118033988749895

In [58]:
# variance
a1.var()

1.25

In [59]:
A.sum()

333

In [60]:
A.mean()

37.0

In [61]:
A.std()

43.96463225012679

In [62]:
A.var()

1932.888888888889

In [63]:
# vertical (column) sum between arrays; 1+10+99, 2+10+99, 3+10+99
A.sum(axis=0)

array([110, 111, 112])

In [64]:
# horizontal (row) sum within arrays; 1+2+3, 10+10+10, 99+99+99
A.sum(axis=1)

array([  6,  30, 297])

In [ ]:
# can do the above vertical & horizontal math with .mean(axis=x), .std(axis=x), .var(axis=x), & many more

# Broadcasting & Vectorized operations

In [ ]:
# really quick operations ("vectorized")

In [65]:
# creates an array from 0 to # (in this case up to 4; NOT including 4)
a2 = np.arange(4)

In [69]:
a2

array([0, 1, 2, 3])

In [70]:
# temporarily adds 10 to all elements in array
a2 + 10

array([10, 11, 12, 13])

In [74]:
# temporarily multiples 10 to all elements in array
a2 * 10

array([ 0, 10, 20, 30])

In [75]:
# despite calculations, arange array will remain the same
a2

array([0, 1, 2, 3])

In [83]:
# permanently adds 100 to all elements in array 
a2 += 100

In [85]:
a2

array([100, 101, 102, 103])

In [86]:
l = [0, 1, 2, 3]

In [89]:
# loop where it multiples 10 to all elements in l array
[i * 10 for i in l]

[0, 10, 20, 30]

In [91]:
b2 = np.arange(4)

In [92]:
b2

array([0, 1, 2, 3])

In [93]:
c2 = np.array([10, 10, 10, 10])

In [94]:
b2 + c2

array([10, 11, 12, 13])

In [96]:
b2 * c2

array([ 0, 10, 20, 30])

# Boolean Arrays 

In [97]:
t = np.arange(4)

In [98]:
t

array([0, 1, 2, 3])

In [99]:
# shows an array including index 0 and last index
t[[0, -1]]

array([0, 3])

In [101]:
# ?
t[[True, False, False, True]]

array([0, 3])