In [3]:
import sys
import numpy as np

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3, 4])

In [6]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
# shows all elements after index 0 (including index 0)
a[0:]

array([1, 2, 3, 4])

In [9]:
# doesn't include index 3 (or 4th position)
a[1:3]

array([2, 3])

In [10]:
# from index 1 to (not including) very last index [-1]
a[1:-1]

array([2, 3])

In [11]:
# shows index 0 and index 2 only
a[::2]

array([1, 3])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:
# an arry of indexes (similar to above execution)
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
# checking data type of array
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
# Unicode (python 3)
c.dtype

dtype('<U1')

In [21]:
# array of an object; not often used for individual objects like this
d = np.array([{'a': 1}, sys])

In [22]:
d.dtype

dtype('O')

# Dimensions & shapes

In [23]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
# 2 by 3 (2 rows/arrays, 3 columns)
A.shape

(2, 3)

In [25]:
# number of dimensions (array(s) inside of a whole array)
A.ndim

2

In [26]:
# total number of elements
A.size

6

In [27]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [28]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [29]:
# 2 by 2 by 3 (2 sections, 2 arrays/rows in each section, 3 columns)
B.shape

(2, 2, 3)

In [30]:
# array(s) inside of array(s) instead of a whole array;
B.ndim

3

In [31]:
# total number of elements
B.size

12

In [32]:
# if dimensions sections are not equal (like below), python will see it as a type object
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\prisc\AppData\Local\Temp/ipykernel_7992/378675374.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [33]:
C.dtype

dtype('O')

In [34]:
C.shape

(2,)

In [35]:
# since it is seen as type object, the sections are seen as single elements
C.size

2

In [36]:
type(C[0])

list

# Indexing & Slicing of Matrices

In [37]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [38]:
# shows all elements in array for index 1
A[1]

array([4, 5, 6])

In [39]:
# shows index 0 of index 1 array
A[1][0]

4

In [40]:
# another way of writing above execution; A[d1, d2, d3, ..., dn]
A[1, 0]

4

In [41]:
# shows arrays from index 0 to index 2 (not including index 2)
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# shows index 0 to 2 (not including 2; ':2') for all arrays (':')
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [43]:
# shows first 2 elements (':2') of first 2 arrays (':2')
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [44]:
# shows last element (index 2; '2:') of first 2 arrays ('2:')
A[:2, 2:]

array([[3],
       [6]])

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# mutable: changing array after it has been assigned; changing index 1 array (2nd position)
A[1] = np.array([10, 10, 10])

In [47]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [48]:
# changes all elements in index 2 array to '99'
A[2] = 99

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary Statistics

In [50]:
a1 = np.array([1, 2, 3, 4])

In [51]:
a1.sum()

10

In [52]:
a1.mean()

2.5

In [53]:
# standard deviation
a1.std()

1.118033988749895

In [54]:
# variance
a1.var()

1.25

In [55]:
A.sum()

333

In [56]:
A.mean()

37.0

In [57]:
A.std()

43.96463225012679

In [58]:
A.var()

1932.888888888889

In [59]:
# vertical (column) sum between arrays; 1+10+99, 2+10+99, 3+10+99
A.sum(axis=0)

array([110, 111, 112])

In [60]:
# horizontal (row) sum within arrays; 1+2+3, 10+10+10, 99+99+99
A.sum(axis=1)

array([  6,  30, 297])

In [61]:
# can do the above vertical & horizontal math with .mean(axis=x), .std(axis=x), .var(axis=x), & many more

# Broadcasting & Vectorized operations

In [62]:
# really quick operations ("vectorized")

In [63]:
# creates an array from 0 to # (in this case up to 4; NOT including 4)
a2 = np.arange(4)

In [64]:
a2

array([0, 1, 2, 3])

In [65]:
# temporarily adds 10 to all elements in array
a2 + 10

array([10, 11, 12, 13])

In [66]:
# temporarily multiples 10 to all elements in array
a2 * 10

array([ 0, 10, 20, 30])

In [67]:
# despite calculations, arange array will remain the same
a2

array([0, 1, 2, 3])

In [68]:
# permanently adds 100 to all elements in array 
a2 += 100

In [69]:
a2

array([100, 101, 102, 103])

In [70]:
l = [0, 1, 2, 3]

In [71]:
# loop where it multiples 10 to all elements in l array
[i * 10 for i in l]

[0, 10, 20, 30]

In [72]:
b2 = np.arange(4)

In [73]:
b2

array([0, 1, 2, 3])

In [74]:
c2 = np.array([10, 10, 10, 10])

In [75]:
b2 + c2

array([10, 11, 12, 13])

In [76]:
b2 * c2

array([ 0, 10, 20, 30])

# Boolean Arrays 

In [77]:
t = np.arange(4)

In [78]:
t

array([0, 1, 2, 3])

In [79]:
# shows an array including index 0 and last index
t[[0, -1]]

array([0, 3])

In [80]:
# using booleans to return values of array; true to show/return, false for NOT showing/returning 
# e.g. show a sub-array of the 1st element and the 4th element
t[[True, False, False, True]]

array([0, 3])

In [81]:
# returns booleans of whether each of elements satisfy the condition
t >= 2

array([False, False,  True,  True])

In [82]:
# returns the values of the array that satisfy the condition
t[t >= 2]

array([2, 3])

In [83]:
t.mean()

1.5

In [84]:
# show all the elements that are greater than the mean
t[t > t.mean()]

array([2, 3])

In [85]:
# show all the elements that are NOT ('~') greater than the mean
t[~(t > t.mean())]

array([0, 1])

In [86]:
t[(t == 0) | (t == 1)]

array([0, 1])

In [87]:
# return values of array where it is less than or equal to two AND where it is divisible by 2
t[(t <= 2) & (t % 2 == 0)]

array([0, 2])

In [88]:
# creates a 3 by 3 array with random numbers from 0 to 100
H = np.random.randint(100, size=(3,3))

In [89]:
H

array([[61, 14, 17],
       [30, 87, 89],
       [18, 34, 86]])

In [90]:
# returns a single sub-array where it says "True"
H[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([61, 17, 87, 18, 86])

In [91]:
H > 30

array([[ True, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [92]:
H[H > 30]

array([61, 87, 89, 34, 86])

# Linear Algebra

In [93]:
C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [94]:
D = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [95]:
# Matrix operations, linear algebra (MATH 1324)
C.dot(D)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [96]:
# same as above
C @ D

array([[20, 14],
       [56, 41],
       [92, 68]])

In [97]:
# transposes/switches columns & rows
C.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [98]:
# but stays the same
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
# transposes the rows/columns of C, then performs dot products with D
C.T @ D

array([[36, 24],
       [48, 33],
       [60, 42]])