In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
# shows all elements after index 0 (including index 0)
a[0:]

array([1, 2, 3, 4])

In [7]:
# doesn't include index 3 (or 4th position)
a[1:3]

array([2, 3])

In [8]:
# from index 1 to (not including) very last index [-1]
a[1:-1]

array([2, 3])

In [9]:
# shows index 0 and index 2 only
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
# an arry of indexes (similar to above execution)
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [12]:
a

array([1, 2, 3, 4])

In [13]:
# checking data type of array
a.dtype

dtype('int32')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [17]:
c = np.array(['a', 'b', 'c'])

In [18]:
# Unicode (python 3)
c.dtype

dtype('<U1')

In [19]:
# array of an object; not often used for individual objects like this
d = np.array([{'a': 1}, sys])

In [20]:
d.dtype

dtype('O')

# Dimensions & shapes

In [21]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [22]:
# 2 by 3 (2 rows/arrays, 3 columns)
A.shape

(2, 3)

In [23]:
# number of dimensions (array(s) inside of a whole array)
A.ndim

2

In [24]:
# total number of elements
A.size

6

In [25]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [26]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [27]:
# 2 by 2 by 3 (2 sections, 2 arrays/rows in each section, 3 columns)
B.shape

(2, 2, 3)

In [28]:
# array(s) inside of array(s) instead of a whole array;
B.ndim

3

In [29]:
# total number of elements
B.size

12

In [30]:
# if dimensions sections are not equal (like below), python will see it as a type object
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\prisc\AppData\Local\Temp/ipykernel_11144/378675374.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [31]:
C.dtype

dtype('O')

In [32]:
C.shape

(2,)

In [33]:
# since it is seen as type object, the sections are seen as single elements
C.size

2

In [34]:
type(C[0])

list

# Indexing & Slicing of Matrices

In [35]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [36]:
# shows all elements in array for index 1
A[1]

array([4, 5, 6])

In [37]:
# shows index 0 of index 1 array
A[1][0]

4

In [38]:
# another way of writing above execution; A[d1, d2, d3, ..., dn]
A[1, 0]

4

In [39]:
# shows arrays from index 0 to index 2 (not including index 2)
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# shows index 0 to 2 (not including 2; ':2') for all arrays (':')
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
# shows first 2 elements (':2') of first 2 arrays (':2')
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [42]:
# shows last element (index 2; '2:') of first 2 arrays ('2:')
A[:2, 2:]

array([[3],
       [6]])

In [43]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# mutable: changing array after it has been assigned; changing index 1 array (2nd position)
A[1] = np.array([10, 10, 10])

In [45]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [46]:
# changes all elements in index 2 array to '99'
A[2] = 99

In [47]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary Statistics

In [48]:
a1 = np.array([1, 2, 3, 4])

In [49]:
a1.sum()

10

In [50]:
a1.mean()

2.5

In [51]:
# standard deviation
a1.std()

1.118033988749895

In [52]:
# variance
a1.var()

1.25

In [53]:
A.sum()

333

In [54]:
A.mean()

37.0

In [55]:
A.std()

43.96463225012679

In [56]:
A.var()

1932.888888888889

In [57]:
# vertical (column) sum between arrays; 1+10+99, 2+10+99, 3+10+99
A.sum(axis=0)

array([110, 111, 112])

In [58]:
# horizontal (row) sum within arrays; 1+2+3, 10+10+10, 99+99+99
A.sum(axis=1)

array([  6,  30, 297])

In [59]:
# can do the above vertical & horizontal math with .mean(axis=x), .std(axis=x), .var(axis=x), & many more

# Broadcasting & Vectorized operations

In [60]:
# really quick operations ("vectorized")

In [61]:
# creates an array from 0 to # (in this case up to 4; NOT including 4)
a2 = np.arange(4)

In [62]:
a2

array([0, 1, 2, 3])

In [63]:
# temporarily adds 10 to all elements in array
a2 + 10

array([10, 11, 12, 13])

In [64]:
# temporarily multiples 10 to all elements in array
a2 * 10

array([ 0, 10, 20, 30])

In [65]:
# despite calculations, arange array will remain the same
a2

array([0, 1, 2, 3])

In [66]:
# permanently adds 100 to all elements in array 
a2 += 100

In [67]:
a2

array([100, 101, 102, 103])

In [68]:
l = [0, 1, 2, 3]

In [69]:
# loop where it multiples 10 to all elements in l array
[i * 10 for i in l]

[0, 10, 20, 30]

In [70]:
b2 = np.arange(4)

In [71]:
b2

array([0, 1, 2, 3])

In [72]:
c2 = np.array([10, 10, 10, 10])

In [73]:
b2 + c2

array([10, 11, 12, 13])

In [74]:
b2 * c2

array([ 0, 10, 20, 30])

# Boolean Arrays 

In [75]:
t = np.arange(4)

In [76]:
t

array([0, 1, 2, 3])

In [77]:
# shows an array including index 0 and last index
t[[0, -1]]

array([0, 3])

In [78]:
# using booleans to return values of array; true to show/return, false for NOT showing/returning 
# e.g. show a sub-array of the 1st element and the 4th element
t[[True, False, False, True]]

array([0, 3])

In [79]:
# returns booleans of whether each of elements satisfy the condition
t >= 2

array([False, False,  True,  True])

In [80]:
# returns the values of the array that satisfy the condition
t[t >= 2]

array([2, 3])

In [81]:
t.mean()

1.5

In [82]:
# show all the elements that are greater than the mean
t[t > t.mean()]

array([2, 3])

In [83]:
# show all the elements that are NOT ('~') greater than the mean
t[~(t > t.mean())]

array([0, 1])

In [84]:
t[(t == 0) | (t == 1)]

array([0, 1])

In [85]:
# return values of array where it is less than or equal to two AND where it is divisible by 2
t[(t <= 2) & (t % 2 == 0)]

array([0, 2])

In [86]:
# creates a 3 by 3 array with random numbers from 0 to 100
H = np.random.randint(100, size=(3,3))

In [87]:
H

array([[28, 51, 86],
       [88, 54, 15],
       [59, 31, 93]])

In [88]:
# returns a single sub-array where it says "True"
H[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([28, 86, 54, 59, 93])

In [89]:
H > 30

array([[False,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [90]:
H[H > 30]

array([51, 86, 88, 54, 59, 31, 93])

# Linear Algebra

In [91]:
C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [92]:
D = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [93]:
# Matrix operations, linear algebra (MATH 1324)
C.dot(D)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [94]:
# same as above
C @ D

array([[20, 14],
       [56, 41],
       [92, 68]])

In [95]:
# transposes/switches columns & rows
C.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [96]:
# but stays the same
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
# transposes the rows/columns of C, then performs dot products with D
C.T @ D

array([[36, 24],
       [48, 33],
       [60, 42]])

# Size of objects in Memory

### Int, Floats

In [98]:
# a regular integer in python takes at least 24 bytes
sys.getsizeof(1)

28

In [99]:
# longs are even larger
sys.getsizeof(10**100)

72

In [100]:
# a NumPy integer takes up much less space than a regularly stored integer
np.dtype(int).itemsize

4

In [101]:
np.dtype(float).itemsize

8

### Lists

In [102]:
# size of a one-element list
sys.getsizeof([1])

64

In [103]:
# size of a NumPy one-element list/array
np.array([1]).itemsize

4

### Time & Performance

In [112]:
# regular list between 0 and 999
l = list(range(100000))

In [113]:
# NumPy array between 0 and 999 
m = np.arange(100000)

In [114]:
# time it takes to perform operation on NumPy array
%time np.sum(m ** 2)

Wall time: 994 µs


216474736

In [115]:
# time it takes to perform operation on regular list
%time sum([x ** 2 for x in l])

Wall time: 117 ms


333328333350000

# Useful NumPy Functions

### random

In [108]:
np.random.random(size=2)

array([0.64736444, 0.71444734])

In [109]:
np.random.normal(size=2)

array([-0.43299946,  0.90613724])

In [110]:
np.random.rand(2, 4)

array([[0.85890408, 0.65121296, 0.04975963, 0.36398384],
       [0.65782529, 0.83084069, 0.08321174, 0.15735217]])

### arange

In [116]:
# create an array from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
# create an array from 5 to 10 (NOT including 10)
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [118]:
# create an array from 0 to 1, incremented by 0.1
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [119]:
# create an array from 0 to 9, then reshape into a 2 by 5 array
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [120]:
# create an array from 0 to 9, then reshape into a 5 by 2 array
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [121]:
# creates a 5-element, equally spaced array, from 0 to 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [122]:
# creates a 20-element, equally spaced array, from 0 to 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [123]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [124]:
# creates a 5 element array, all zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [125]:
# creates a 3 by 3 array, all zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [127]:
# creates a 3 by 3 array, all zeros & changes data type from decimal float to whole int
np.zeros((3,3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [128]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [129]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [130]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [131]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### identity and eye

In [132]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [135]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [137]:
'Hello World'[6]

'W'